/**
 * TypeScript Type Generator for Neon DB
 *
 * This script connects to Neon DB and generates TypeScript interfaces
 * for all database tables by querying the information_schema.
 *
 * Generates three type variants for each table:
 * - Row: Complete record type with all fields
 * - Insert: Type for inserting new records (auto-generated fields optional)
 * - Update: Type for updating records (all fields optional)
 *
 * Requirements: 5.1, 5.4
 */

import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';
import { config } from 'dotenv';

// Load environment variables from .env file
config();

interface ColumnInfo {
  columnName: string;
  dataType: string;
  isNullable: boolean;
  columnDefault: string | null;
  isIdentity: boolean;
}

interface ForeignKeyInfo {
  columnName: string;
  referencedTable: string;
  referencedColumn: string;
}

interface TableInfo {
  tableName: string;
  columns: ColumnInfo[];
  foreignKeys: ForeignKeyInfo[];
}

/**
 * Map PostgreSQL data types to TypeScript types
 */
function mapPostgreSQLTypeToTypeScript(pgType: string): string {
  const typeMap: Record<string, string> = {
    // String types
    text: 'string',
    'character varying': 'string',
    varchar: 'string',
    char: 'string',
    character: 'string',

    // Numeric types
    integer: 'number',
    int: 'number',
    smallint: 'number',
    bigint: 'number',
    decimal: 'number',
    numeric: 'number',
    real: 'number',
    'double precision': 'number',
    serial: 'number',
    bigserial: 'number',

    // Boolean
    boolean: 'boolean',
    bool: 'boolean',

    // Date/Time types
    timestamp: 'string',
    'timestamp without time zone': 'string',
    'timestamp with time zone': 'string',
    timestamptz: 'string',
    date: 'string',
    time: 'string',
    'time without time zone': 'string',
    'time with time zone': 'string',
    timetz: 'string',

    // UUID
    uuid: 'string',

    // JSON types
    json: 'any',
    jsonb: 'any',

    // Array types
    ARRAY: 'any[]',
  };

  return typeMap[pgType.toLowerCase()] || 'any';
}

/**
 * Connect to Neon DB and retrieve table information
 */
async function getTableInfo(pool: Pool, tableName: string): Promise<TableInfo> {
  // Query column information
  const columnQuery = `
    SELECT 
      column_name,
      data_type,
      is_nullable,
      column_default,
      is_identity
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = $1
    ORDER BY ordinal_position;
  `;

  const columnResult = await pool.query(columnQuery, [tableName]);

  const columns: ColumnInfo[] = columnResult.rows.map((row) => ({
    columnName: row.column_name,
    dataType: row.data_type,
    isNullable: row.is_nullable === 'YES',
    columnDefault: row.column_default,
    isIdentity: row.is_identity === 'YES',
  }));

  // Query foreign key relationships
  const fkQuery = `
    SELECT
      kcu.column_name,
      ccu.table_name AS referenced_table,
      ccu.column_name AS referenced_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_schema = 'public'
      AND tc.table_name = $1;
  `;

  const fkResult = await pool.query(fkQuery, [tableName]);

  const foreignKeys: ForeignKeyInfo[] = fkResult.rows.map((row) => ({
    columnName: row.column_name,
    referencedTable: row.referenced_table,
    referencedColumn: row.referenced_column,
  }));

  return {
    tableName,
    columns,
    foreignKeys,
  };
}

/**
 * Get all table names from the database
 */
async function getAllTableNames(pool: Pool): Promise<string[]> {
  const query = `
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
    ORDER BY table_name;
  `;

  const result = await pool.query(query);
  return result.rows.map((row) => row.table_name);
}

/**
 * Check if a column is auto-generated (has default value or is identity)
 */
function isAutoGenerated(column: ColumnInfo): boolean {
  return (
    column.isIdentity ||
    (column.columnDefault !== null &&
      (column.columnDefault.includes('gen_random_uuid()') ||
        column.columnDefault.includes('now()') ||
        column.columnDefault.includes('CURRENT_') ||
        column.columnDefault.includes('nextval')))
  );
}

/**
 * Generate TypeScript interface for a table
 */
function generateTableTypes(tableInfo: TableInfo): string {
  const { tableName, columns, foreignKeys } = tableInfo;

  // Convert table name to PascalCase for type names
  const typeName = tableName
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');

  let output = '';

  // Add JSDoc comment with table description
  output += `/**\n`;
  output += ` * Database table: ${tableName}\n`;
  if (foreignKeys.length > 0) {
    output += ` * Foreign keys:\n`;
    foreignKeys.forEach((fk) => {
      output += ` *   - ${fk.columnName} -> ${fk.referencedTable}.${fk.referencedColumn}\n`;
    });
  }
  output += ` */\n`;

  // Generate Row type (complete record)
  output += `export interface ${typeName}Row {\n`;
  columns.forEach((col) => {
    const tsType = mapPostgreSQLTypeToTypeScript(col.dataType);
    const nullableSuffix = col.isNullable ? ' | null' : '';
    output += `  ${col.columnName}: ${tsType}${nullableSuffix};\n`;
  });
  output += `}\n\n`;

  // Generate Insert type (auto-generated fields are optional)
  output += `/**\n`;
  output += ` * Type for inserting new ${tableName} records\n`;
  output += ` * Auto-generated fields (id, timestamps) are optional\n`;
  output += ` */\n`;
  output += `export interface ${typeName}Insert {\n`;
  columns.forEach((col) => {
    const tsType = mapPostgreSQLTypeToTypeScript(col.dataType);
    const isOptional = isAutoGenerated(col) || col.isNullable;
    const optionalMarker = isOptional ? '?' : '';
    const nullableSuffix = col.isNullable ? ' | null' : '';
    output += `  ${col.columnName}${optionalMarker}: ${tsType}${nullableSuffix};\n`;
  });
  output += `}\n\n`;

  // Generate Update type (all fields optional)
  output += `/**\n`;
  output += ` * Type for updating ${tableName} records\n`;
  output += ` * All fields are optional\n`;
  output += ` */\n`;
  output += `export interface ${typeName}Update {\n`;
  columns.forEach((col) => {
    const tsType = mapPostgreSQLTypeToTypeScript(col.dataType);
    const nullableSuffix = col.isNullable ? ' | null' : '';
    output += `  ${col.columnName}?: ${tsType}${nullableSuffix};\n`;
  });
  output += `}\n\n`;

  return output;
}

/**
 * Main function to generate types
 */
async function generateTypes() {
  console.log('Starting TypeScript type generation...\n');

  // Load database configuration
  const connectionString = process.env.NEON_DATABASE_URL;
  if (!connectionString) {
    throw new Error('NEON_DATABASE_URL environment variable is required');
  }

  // Create database connection pool
  const pool = new Pool({ connectionString });

  try {
    // Test connection
    await pool.query('SELECT 1');
    console.log('✓ Connected to Neon DB\n');

    // Get all table names
    const tableNames = await getAllTableNames(pool);
    console.log(
      `Found ${tableNames.length} tables: ${tableNames.join(', ')}\n`,
    );

    // Generate types for each table
    let output = '';
    output += '/**\n';
    output += ' * Auto-generated TypeScript types for Neon DB\n';
    output +=
      ' * Generated from database schema using scripts/generate-types.ts\n';
    output += ' * \n';
    output += ' * DO NOT EDIT THIS FILE MANUALLY\n';
    output += ' * Run `npm run generate:types` to regenerate\n';
    output += ' */\n\n';

    for (const tableName of tableNames) {
      console.log(`Generating types for table: ${tableName}`);
      const tableInfo = await getTableInfo(pool, tableName);
      output += generateTableTypes(tableInfo);
    }

    // Write to output file
    const outputPath = path.join(process.cwd(), 'src', 'lib', 'db', 'types.ts');
    fs.writeFileSync(outputPath, output, 'utf-8');

    console.log(`\n✓ Types generated successfully!`);
    console.log(`  Output: ${outputPath}`);
    console.log(`  Tables processed: ${tableNames.length}`);
  } catch (error) {
    console.error('Error generating types:', error);
    throw error;
  } finally {
    await pool.end();
  }
}

// Run the generator if this file is executed directly
const isMainModule = import.meta.url === `file://${process.argv[1]}`;

if (isMainModule) {
  generateTypes()
    .then(() => {
      console.log('\n✓ Type generation complete');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n✗ Type generation failed:', error);
      process.exit(1);
    });
}

export { generateTypes };
